Repository Dev-Pepes/playlist_be, pull requests merged in 2023-09, with the labels that each got.

#2 chore : 빌드과정 수정
  .gitignore
  Api/src/main/resources/application.yml
  Dockerfile
  docker-compose-local.yml
  docker-compose.yml
  mysql/conf.d/my.cnf
  mysql/data/.keep
  mysql/initdb.d/user.sql
Labels: feat

#3 fix : Docker-compose 빌드 관련해서 문제있는 사항 수정
  .gitignore
  Api/src/main/resources/application.yml
  Dockerfile
  Domain/build.gradle
  build.gradle
  docker-compose-local.yml
Labels: wontfix

#12 spotless test
  .github/workflows/ci.yml
Labels: feat

#13 spotless apply README 명시
  README.md
Labels: docs

#18 게시판, 게시글 관련 Entity 작성
  Domain/src/main/java/playlist/server/domain/domains/AbstractTimeStamp.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/Article.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/ArticleBookmark.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/ArticleLike.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/ArticleStatus.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/Board.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/BoardType.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/ArticleBookmarkRepository.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/ArticleLikeRepository.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/ArticleRepository.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/BoardRepository.java
Labels: enhancement, feat

#21 [feat] DBDocs CD, DBML추가
  .github/workflows/DBDOCS_BUILD.yml
  Docs/10duck.dbml
Labels: enhancement, feat

#26 fix: Board, Article, Reply 관련 테이블 dbml 수정 #25
  Docs/10duck.dbml
Labels: docs, enhancement

#32 [FIX] Dbml group 수정
  Docs/10duck.dbml
Labels: bug, docs

#35 [FEATURE] ArticleTag Entity 수정, 리팩토링
  Domain/src/main/java/playlist/server/domain/domains/board/domain/HashTag.java
  Domain/src/main/java/playlist/server/domain/domains/board/domain/TagList.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/HashTagRepository.java
  Domain/src/main/java/playlist/server/domain/domains/board/repository/TagListRepository.java
  Domain/src/main/java/playlist/server/domain/domains/playlist/domain/Playlist.java
  Domain/src/main/java/playlist/server/domain/domains/playlist/domain/PlaylistTag.java
  Domain/src/main/java/playlist/server/domain/domains/playlist/repository/PlaylistTagRepository.java
Labels: enhancement, feat
